CREATE TABLE STORES
    ( 
     STORE_ID       VARCHAR2 (20 CHAR)  NOT NULL , 
     STORE_NAME     VARCHAR2 (50 CHAR)  NOT NULL , 
     CATEGORY_CODE  INTEGER  NOT NULL , 
     SEAT_NUM       INTEGER  NOT NULL , 
     SERVICE_TIME   VARCHAR2 (50 CHAR) ,
     IMAGE_URL      VARCHAR2 (50 CHAR) 
    )
;


CREATE TABLE STORES_LOCATION
   (
     STORE_ID       VARCHAR2 (20 CHAR)  NOT NULL , 
     STORE_LOCATION VARCHAR2 (50 CHAR)  NOT NULL , 
     LONGITUDE      VARCHAR2 (50 CHAR)  NOT NULL ,
     LATITUDE       VARCHAR2 (50 CHAR)  NOT NULL
    )
;

CREATE TABLE CATEGORY
    ( 
     CATEGORY_CODE INTEGER  NOT NULL , 
     CATEGORY_NAME VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

CREATE TABLE MENU
    ( 
     STORE_ID  VARCHAR2 (20 CHAR)  NOT NULL , 
     MENU_NAME VARCHAR2 (30 CHAR)  NOT NULL , 
     PRICE     INTEGER  NOT NULL 
    ) 
;


CREATE TABLE STORE_SEAT
    ( 
     STORE_ID      VARCHAR2 (20 CHAR)  NOT NULL , 
     IN_USING_SEAT INTEGER  NOT NULL 
    ) 
;

CREATE TABLE REVIEW
    ( 
     REVIEW_ID INTEGER  NOT NULL ,
     STORE_ID  VARCHAR2 (20 CHAR)  NOT NULL , 
     USER_ID   VARCHAR2 (15 CHAR)  NOT NULL , 
     "COMENT" VARCHAR2 (50 CHAR) , 
     SCORE     INTEGER  NOT NULL
    ) 
;

CREATE TABLE FAV_STORE
    ( 
     STORE_ID     VARCHAR2 (20 CHAR)  NOT NULL , 
     USER_ID      VARCHAR2 (15 CHAR)  NOT NULL , 
     FAV_STORE_ID INTEGER  NOT NULL 
    ) 
;

CREATE TABLE DELETE_FAIL_LOG_STORE (
    store_id VARCHAR2 (20),
    fail_msg VARCHAR2(4000),
    fail_time TIMESTAMP
);
