CREATE OR REPLACE TRIGGER TRG_STORES_DELETE
AFTER DELETE ON STORES
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_err_msg VARCHAR2(4000);
BEGIN
    BEGIN
        DELETE FROM BOOKING_ADMIN.BOOKING@PDB_BOOKING_LINK
        WHERE STORE_ID = :OLD.STORE_ID;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            v_err_msg := SQLERRM;
            INSERT INTO STORE_ADMIN.delete_fail_log(STORE_ID, fail_msg, fail_time)
            VALUES (:OLD.STORE_ID, v_err_msg, SYSTIMESTAMP);
            COMMIT;
    END;
END;
/
