CREATE TABLE BOOKING 
    ( 
     BOOKING_NUM        INTEGER  NOT NULL , 
     BOOKING_DATE       TIMESTAMP NOT NULL,
     USER_ID            VARCHAR2 (15 CHAR)  NOT NULL , 
     STORE_ID           VARCHAR2 (20)  NOT NULL , 
     BOOKING_STATE_CODE INTEGER  NOT NULL , 
     COUNT              INTEGER  NOT NULL 
    ) 
;


CREATE TABLE BOOKING_STATE_CODE 
    ( 
     BOOKING_STATE_CODE INTEGER  NOT NULL , 
     STATE_NAME         VARCHAR2 (10)  NOT NULL 
    ) 
;


CREATE SEQUENCE BOOKING_BOOKING_NUM_SEQ 
    START WITH 1 
    INCREMENT BY 1
    NOCACHE 
    ORDER ;


ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_PK PRIMARY KEY ( BOOKING_NUM ) ;
