CREATE TABLE STORES 
    ( 
     STORE_ID       VARCHAR2 (20 CHAR)  NOT NULL , 
     STORE_NAME     VARCHAR2 (50 CHAR)  NOT NULL , 
     CATEGORY_CODE  INTEGER  NOT NULL , 
     STORE_LOCATION VARCHAR2 (50 CHAR)  NOT NULL , 
     SEAT_NUM       INTEGER  NOT NULL , 
     SERVICE_TIME   VARCHAR2 (50 CHAR) 
    ) 
;

ALTER TABLE STORES 
    ADD CONSTRAINT STORES_PK PRIMARY KEY ( STORE_ID ) ;

ALTER TABLE STORES 
    ADD CONSTRAINT STORES_CATEGORY_FK FOREIGN KEY 
    ( 
     CATEGORY_CODE
    ) 
    REFERENCES CATEGORY 
    ( 
     CATEGORY_CODE
    ) 
;

---------------------------------------------------------------------------
CREATE TABLE CATEGORY 
    ( 
     CATEGORY_CODE INTEGER  NOT NULL , 
     CATEGORY_NAME VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE CATEGORY 
    ADD CONSTRAINT CATEGORY_PK PRIMARY KEY ( CATEGORY_CODE ) ;

------------------------------------------------------------------------------
CREATE TABLE MENU 
    ( 
     STORE_ID  VARCHAR2 (20 CHAR)  NOT NULL , 
     MENU_NAME VARCHAR2 (30 CHAR)  NOT NULL , 
     PRICE     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE MENU 
    ADD CONSTRAINT MENU_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;
------------------------------------------------------------------------------------
CREATE TABLE STORE_SEAT 
    ( 
     STORE_ID      VARCHAR2 (20 CHAR)  NOT NULL , 
     IN_USING_SEAT INTEGER  NOT NULL 
    ) 
;

ALTER TABLE STORE_SEAT 
    ADD CONSTRAINT STORE_SEAT_PK PRIMARY KEY ( STORE_ID ) ;

ALTER TABLE STORE_SEAT 
    ADD CONSTRAINT STORE_SEAT_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;

-------------------------------------------------------------------------------------------
CREATE TABLE REVIEW 
    ( 
     STORE_ID  VARCHAR2 (20 CHAR)  NOT NULL , 
     USER_ID   VARCHAR2 (15 CHAR)  NOT NULL , 
     "COMMENT" VARCHAR2 (50 CHAR) , 
     RATIO     INTEGER  NOT NULL , 
     REVIEW_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE REVIEW 
    ADD 
    CHECK (RATIO BETWEEN 1 AND 10) 
;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_PK PRIMARY KEY ( REVIEW_ID ) ;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW__UN UNIQUE ( USER_ID , STORE_ID ) ;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_MV_USERS_FK FOREIGN KEY 
    ( 
     USER_ID
    ) 
    REFERENCES MV_USERS 
    ( 
     USER_ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;

CREATE SEQUENCE REVIEW_REVIEW_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER REVIEW_REVIEW_ID_TRG 
BEFORE INSERT ON REVIEW 
FOR EACH ROW 
WHEN (NEW.REVIEW_ID IS NULL) 
BEGIN 
    :NEW.REVIEW_ID := REVIEW_REVIEW_ID_SEQ.NEXTVAL; 
END;
/

-----------------------------------------------------------------------------
CREATE TABLE FAV_STORE 
    ( 
     STORE_ID     VARCHAR2 (20 CHAR)  NOT NULL , 
     USER_ID      VARCHAR2 (15 CHAR)  NOT NULL , 
     FAV_STORE_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE FAV_STORE 
    ADD CONSTRAINT FAV_STORE_PK PRIMARY KEY ( FAV_STORE_ID ) ;

ALTER TABLE FAV_STORE 
    ADD CONSTRAINT FAV_STORE__UN UNIQUE ( STORE_ID , USER_ID ) ;

ALTER TABLE FAV_STORE 
    ADD CONSTRAINT FAV_STORE_MV_USERS_FK FOREIGN KEY 
    ( 
     USER_ID
    ) 
    REFERENCES MV_USERS 
    ( 
     USER_ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE FAV_STORE 
    ADD CONSTRAINT FAV_STORE_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;

CREATE SEQUENCE FAV_STORE_FAV_STORE_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER FAV_STORE_FAV_STORE_ID_TRG 
BEFORE INSERT ON FAV_STORE 
FOR EACH ROW 
WHEN (NEW.FAV_STORE_ID IS NULL) 
BEGIN 
    :NEW.FAV_STORE_ID := FAV_STORE_FAV_STORE_ID_SEQ.NEXTVAL; 
END;
/





