ALTER TABLE FAV_STORE 
    ADD CONSTRAINT FAV_STORE_PK PRIMARY KEY ( FAV_STORE_ID ) ;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_STORE_USER_UN UNIQUE ( STORE_ID , USER_ID ) ;

ALTER TABLE FAV_STORE 
    ADD CONSTRAINT FAV_STORE_UN UNIQUE ( STORE_ID , USER_ID ) ;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_PK PRIMARY KEY ( REVIEW_ID ) ;

ALTER TABLE STORES 
    ADD CONSTRAINT STORES_PK PRIMARY KEY ( STORE_ID ) ;

ALTER TABLE CATEGORY 
    ADD CONSTRAINT CATEGORY_PK PRIMARY KEY ( CATEGORY_CODE ) ;

ALTER TABLE STORE_SEAT 
    ADD CONSTRAINT STORE_SEAT_PK PRIMARY KEY ( STORE_ID ) ;

ALTER TABLE  STORES_LOCATION
    ADD CONSTRAINT STORES_LOCATIONT_PK PRIMARY KEY ( STORE_ID ) ;


ALTER TABLE STORES 
    ADD CONSTRAINT STORES_CATEGORY_FK FOREIGN KEY 
    ( 
     CATEGORY_CODE
    ) 
    REFERENCES CATEGORY 
    ( 
     CATEGORY_CODE
    ) 
;

ALTER TABLE MENU 
    ADD CONSTRAINT MENU_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE STORES_LOCATION ADD CONSTRAINT STORES_LOCATION_FK FOREIGN KEY 
     ( 
      STORE_ID
     ) 
     REFERENCES STORES 
     ( 
      STORE_ID
     ) 
     ON DELETE CASCADE 
;


ALTER TABLE STORE_SEAT 
    ADD CONSTRAINT STORE_SEAT_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE FAV_STORE 
    ADD CONSTRAINT FAV_STORE_MV_USERS_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;



CREATE DATABASE LINK PDB_BOOKING_LINK
CONNECT TO BOOKING_ADMIN IDENTIFIED BY oracle
USING 'PDB_BOOKING';
