CREATE MATERIALIZED VIEW MV_USERS_FAV_STORES
REFRESH FAST ON DEMAND
AS
SELECT * FROM FAV_STORE@PDB_STORES_LINK;

CREATE MATERIALIZED VIEW MV_USERS_REVIEW
REFRESH FAST ON DEMAND
AS
SELECT * FROM REVIEW@PDB_STORES_LINK;
