CREATE VIEW V_FAV_STORE
AS
SELECT * FROM FAV_STORE@PDB_STORES_LINK;

CREATE VIEW V_REVIEW
AS
SELECT * FROM REVIEW@PDB_STORES_LINK;

CREATE VIEW V_STORES
AS
SELECT * FROM STORES@PDB_STORES_LINK;

CREATE VIEW V_CATEGORY
AS
SELECT * FROM CATEGORY@PDB_STORES_LINK;

CREATE VIEW V_BOOKING
AS
SELECT * FROM BOOKING@PDB_BOOKING_LINK;

CREATE VIEW V_BOOKING_STATE_CODE
AS
SELECT * FROM BOOKING_STATE_CODE@PDB_BOOKING_LINK;


CREATE VIEW V_USER_BOOKINGS AS
SELECT
    b.BOOKING_NUM,
    b.USER_ID,
    b.STORE_ID,
    s.STORE_NAME,
    b.BOOKING_DATE,
    b.BOOKING_STATE_CODE,
    bs.STATE_NAME
FROM V_BOOKING b
JOIN V_STORES s ON b.STORE_ID = s.STORE_ID
JOIN V_BOOKING_STATE_CODE bs ON b.BOOKING_STATE_CODE = bs.BOOKING_STATE_CODE;



CREATE VIEW V_USER_FAVORITE_COUNT AS
SELECT 
    u.USER_ID,
    COALESCE(fav_count.COUNT, 0) AS TOTAL_FAVORITES
FROM USERS u
LEFT JOIN (
    SELECT USER_ID, COUNT(*) AS COUNT 
    FROM V_FAV_STORE
    GROUP BY USER_ID
) fav_count ON u.USER_ID = fav_count.USER_ID;




CREATE VIEW V_USER_REVIEW_COUNT AS
SELECT 
    u.USER_ID,
    COALESCE(review_count.COUNT, 0) AS TOTAL_REVIEWS
FROM USERS u
LEFT JOIN (
    SELECT USER_ID, COUNT(*) AS COUNT 
    FROM V_REVIEW
    GROUP BY USER_ID
) review_count ON u.USER_ID = review_count.USER_ID;



CREATE VIEW V_USER_BOOKING_COUNT AS
SELECT 
    u.USER_ID,
    COALESCE(booking_count.COUNT, 0) AS TOTAL_BOOKINGS
FROM USERS u
LEFT JOIN (
    SELECT USER_ID, COUNT(*) AS COUNT 
    FROM V_BOOKING
    GROUP BY USER_ID
) booking_count ON u.USER_ID = booking_count.USER_ID;




-- 보류
CREATE VIEW V_USER_ACTIVE_BOOKING_COUNT AS
SELECT 
    u.USER_ID,
    COALESCE(active_booking_count.COUNT, 0) AS ACTIVE_BOOKINGS
FROM USERS u
LEFT JOIN (
    SELECT b.USER_ID, COUNT(*) AS COUNT 
    FROM V_BOOKING b
    JOIN V_BOOKING_STATE_CODE bsc 
        ON b.BOOKING_STATE_CODE = bsc.BOOKING_STATE_CODE
    WHERE bsc.BOOKING_STATE_CODE = 'ACTIVE'
    GROUP BY b.USER_ID
) active_booking_count ON u.USER_ID = active_booking_count.USER_ID;



------------------취소-----------------------


CREATE MATERIALIZED VIEW MV_USERS_FAV_STORES
REFRESH FAST ON DEMAND
AS
SELECT * FROM FAV_STORE@PDB_STORES_LINK;

CREATE MATERIALIZED VIEW MV_USERS_REVIEW
REFRESH FAST ON DEMAND
AS
SELECT * FROM REVIEW@PDB_STORES_LINK;

USER_PDB
MV 삭제
DROP MATERIALIZED VIEW MV_USERS_FAV_STORES;
DROP MATERIALIZED VIEW MV_USERS_REVIEW;


STORE_PDB
MV LOG 삭제
DROP MATERIALIZED VIEW LOG ON FAV_STORE;
DROP MATERIALIZED VIEW LOG ON REVIEW;


ALTER TABLE FAV_STORE ADD STORE_NAME VARCHAR(50) NOT NULL;
ALTER TABLE REVIEW ADD STORE_NAME VARCHAR(50) NOT NULL;


CREATE VIEW V_FAV_STORE AS SELECT * FROM FAV_STORE@PDB_STORES_LINK;
CREATE VIEW V_REVIEW AS SELECT * FROM REVIEW@PDB_STORES_LINK;
