CREATE TABLE USERS 
    ( 
     USER_ID       VARCHAR2 (50 CHAR)  NOT NULL , 
     USER_NAME     VARCHAR2 (20 CHAR)  NOT NULL , 
     PHONE_NUMBER  VARCHAR2 (20 CHAR)  NOT NULL , 
     USER_LOCATION VARCHAR2 (50 CHAR) , 
     PASSWORD      VARCHAR2 (255 CHAR)  NOT NULL 
    ) 
;


CREATE TABLE DELETE_FAIL_LOG_USER (
    user_id varchar2(50),
    fail_msg VARCHAR2(4000),
    fail_time TIMESTAMP
);


CREATE MATERIALIZED VIEW MV_USERS_FAV_STORES
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT * FROM FAV_STORE@PDB_STORES_LINK;

ALTER TABLE USERS 
    ADD CONSTRAINT USERS_PK PRIMARY KEY ( USER_ID ) ;


CREATE DATABASE LINK PDB_USERS_LINK
CONNECT TO USER_ADMIN IDENTIFIED BY oracle
USING 'PDB_USER';

