CREATE MATERIALIZED VIEW MV_USERS_FAV_STORES
REFRESH FAST ON DEMAND
AS
SELECT * FROM FAV_STORE@PDB_STORES_LINK;

CREATE MATERIALIZED VIEW MV_USERS_REVIEW
REFRESH FAST ON DEMAND
AS
SELECT * FROM REVIEW@PDB_STORES_LINK;

USER_PDB
MV 삭제
DROP MATERIALIZED VIEW MV_USERS_FAV_STORES;
DROP MATERIALIZED VIEW MV_USERS_REVIEW;


STORE_PDB
MV LOG 삭제
DROP MATERIALIZED VIEW LOG ON FAV_STORE;
DROP MATERIALIZED VIEW LOG ON REVIEW;


ALTER TABLE FAV_STORE ADD STORE_NAME VARCHAR(50) NOT NULL;
ALTER TABLE REVIEW ADD STORE_NAME VARCHAR(50) NOT NULL;


CREATE VIEW V_FAV_STORE AS SELECT * FROM FAV_STORE@PDB_STORES_LINK;
CREATE VIEW V_REVIEW AS SELECT * FROM REVIEW@PDB_STORES_LINK;
