CREATE TABLE STORES 
    ( 
     STORE_ID       VARCHAR2 (20 CHAR)  NOT NULL , 
     STORE_NAME     VARCHAR2 (50 CHAR)  NOT NULL , 
     CATEGORY_CODE  INTEGER  NOT NULL , 
     STORE_LOCATION VARCHAR2 (50 CHAR)  NOT NULL , 
     SEAT_NUM       INTEGER  NOT NULL , 
     SERVICE_TIME   DATE 
    ) 
;

ALTER TABLE STORES 
    ADD CONSTRAINT STORES_PK PRIMARY KEY ( STORE_ID ) ;

ALTER TABLE STORES 
    ADD CONSTRAINT STORES_CATEGORY_FK FOREIGN KEY 
    ( 
     CATEGORY_CODE
    ) 
    REFERENCES CATEGORY 
    ( 
     CATEGORY_CODE
    ) 
;

---------------------------------------------------------------------------
CREATE TABLE CATEGORY 
    ( 
     CATEGORY_CODE INTEGER  NOT NULL , 
     CATEGORY_NAME VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE CATEGORY 
    ADD CONSTRAINT CATEGORY_PK PRIMARY KEY ( CATEGORY_CODE ) ;

------------------------------------------------------------------------------
CREATE TABLE MENU 
    ( 
     STORE_ID  VARCHAR2 (20 CHAR)  NOT NULL , 
     MENU_NAME VARCHAR2 (30 CHAR)  NOT NULL , 
     PRICE     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE MENU 
    ADD CONSTRAINT MENU_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;
------------------------------------------------------------------------------------
CREATE TABLE STORE_SEAT 
    ( 
     STORE_ID      VARCHAR2 (20 CHAR)  NOT NULL , 
     IN_USING_SEAT INTEGER  NOT NULL 
    ) 
;

ALTER TABLE STORE_SEAT 
    ADD CONSTRAINT STORE_SEAT_PK PRIMARY KEY ( STORE_ID ) ;

ALTER TABLE STORE_SEAT 
    ADD CONSTRAINT STORE_SEAT_STORES_FK FOREIGN KEY 
    ( 
     STORE_ID
    ) 
    REFERENCES STORES 
    ( 
     STORE_ID
    ) 
    ON DELETE CASCADE 
;

